services:
  web:
    image: nginx
    ports:
      - 8081:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    restart: always
    depends_on:
      - php-fpm
      - postgres_db

  php-fpm:
    build: ./docker/php/
    volumes:
      - .:/var/www/html
#      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-xdebug.ini

  postgres_db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
